name: Docs
on:
  pull_request:
    paths: ["docs/**"]
  push:
    branches: ["main"]
    paths: ["docs/**"]
  workflow_dispatch: {}

env:
  PUPPETEER_SKIP_DOWNLOAD: 1
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

jobs:
  lint:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        if: github.event_name != 'pull_request'
      - uses: actions/checkout@v5
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: ./action.yml
        with:
          SOURCE: docs/index.html
          DESTINATION: index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
