name: Docs
on:
  pull_request:
    paths: ["docs/**"]
  push:
    branches: ["main"]
    paths: ["docs/**"]
  workflow_dispatch: {}

env:
  PUPPETEER_SKIP_DOWNLOAD: 1
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome

jobs:
  lint:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Get ref to checkout
        id: ref
        run: |
          echo "ref=${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v5
        with:
          ref: ${{ steps.ref.outputs.ref }}

      - uses: './'
        with:
          SOURCE: docs/index.html
          DESTINATION: index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
